// AUTO-GENERATED by runGoalIntegrationBenchmark.ts -- do not hand-edit.
// Browser-safe (no `fs`): the ELIGIBLE, priority-sorted Goal strategies
// that passed Solver Integration Sprint v1's section 6 gate
// (Expected WrongWing 감소 > 0 AND Replay Success Rate >= 60% AND
// Regression Rate <= 20%), computed against all 75 real Failure Replays.
// Regenerate via: npx tsx src/customCube/runGoalIntegrationBenchmark.ts
import type { PortableGoal } from "./GoalDescriptor";

export const ELIGIBLE_GOALS: PortableGoal[] = [];
